![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [18]:
my_array = np.arange(10)
print(my_array)
print(my_array[-1::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [19]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [20]:
print(my_array[-8:-11:-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [31]:
matriz = np.array([[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]])

print(matriz)
print(matriz[::-1,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [35]:
print(matriz[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [59]:
print(matriz)

print(matriz[::2,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [66]:
print(matriz[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [71]:
animales = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x1 = list(filter(lambda x: x == "Loro", animales))
print(x1)

x2 = animales == "Loro"
print(animales[x2])


['Loro', 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [73]:
matriz = np.array([[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]])

matriz.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [75]:
matriz_1 = np.arange(20)
matriz_1.reshape (2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [77]:
matriz = np.array([[1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]])

print(matriz[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

In [81]:
array_10 = np.zeros((2,5))
print(array_10)

print(array_10.nbytes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
80


## Ejercicio 12
Crea un vector que vaya del 10 al 49 e inviértelo

In [83]:
vector = np.arange(10,50)
print(vector)
print(np.flip(vector))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4].

Resuelvelo como quieras, pero hay un [método apropiado en la documentación.](https://numpy.org/doc/)  Si quieres, búscalo.

In [84]:
vector_13 = np.array([1,2,0,0,4,0])

print(np.where (vector_13 != 0))



(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo. 

In [94]:
matriz_14 = np.random.randint(1,100,size = (10,10))
print(matriz_14)


[[ 6 81 69 74 50 26 85 92 73  6]
 [65 13 81 27 48 54 98 97 37 72]
 [66 96 30 83 16 85 57  8 87 98]
 [85  4 73 28 38 14 32 70 52 38]
 [ 6  3 76 54 23 23 66 77 53 99]
 [34 96 82 76 54 38 31 63 63 27]
 [32 27  7 65 41 17 77 52 15 75]
 [68 19 85 29 38 43 24 90  4 85]
 [55 59 30 43 26  5 90 67 56 59]
 [ 6 30 98 43 65 93 99 40 47 78]]


In [99]:
np.min(matriz_14), np.max(matriz_14)


(3, 99)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [102]:
vector_rand = np.random.rand(30)
print(vector_rand)
np.mean(vector_rand)


[0.67307973 0.03708612 0.25317272 0.99923974 0.52681272 0.45900864
 0.41779871 0.60912165 0.32098861 0.40342583 0.07814372 0.47056582
 0.94138178 0.28745864 0.67179581 0.02616282 0.38415336 0.19118203
 0.62832894 0.46493378 0.9592736  0.39374725 0.58952564 0.07930731
 0.95739142 0.32342757 0.88191157 0.61058068 0.1126218  0.82223625]


0.4857954746555892

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s.

Ej:

```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

```



In [2]:
import numpy as np

In [4]:
cuadrado = np.array ([[1,1,1,1,1],
                    [1,0,0,0,1],
                    [1,0,0,0,1],
                    [1,0,0,0,1],
                    [1,1,1,1,1]])

print(cuadrado)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [5]:
matrix_cuadrado = np.array ([[0,1,0,1,0,1,0,1], 
                            [1,0,1,0,1,0,1,0],
                            [0,1,0,1,0,1,0,1],
                            [1,0,1,0,1,0,1,0],
                            [0,1,0,1,0,1,0,1],
                            [1,0,1,0,1,0,1,0],
                            [0,1,0,1,0,1,0,1],
                            [1,0,1,0,1,0,1,0]])
print(matrix_cuadrado)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [12]:
ejer_18 = np.array ([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]])
new_18 = np.tile(ejer_18, (8,8))
print(new_18)

[[0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [7]:
np.random.seed(2022)
mat_rand = np.random.randint(1,100,size = (5,5))
print(mat_rand)

normal_1 = mat_rand  - mat_rand.mean() 
normal_2 = normal_1 / mat_rand.std()

print(normal_2)

[[93 46 50 56 89]
 [19 25 17 54 42]
 [34 28 12 20 95]
 [76 49 20 39 73]
 [15 94 17 91 12]]
[[ 1.61480138 -0.02229234  0.11703479  0.32602547  1.47547426]
 [-0.96275044 -0.75375975 -1.032414    0.25636191 -0.16161947]
 [-0.44027372 -0.6492644  -1.20657291 -0.92791866  1.68446495]
 [ 1.0226611   0.082203   -0.92791866 -0.26611481  0.91816576]
 [-1.10207756  1.64963317 -1.032414    1.54513782 -1.20657291]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.


In [18]:
my_array = np.arange(10)
new_array = my_array.copy()

new_array[np.where ((new_array >=3) & (new_array <=8))] = -1
print(new_array)


[ 0  1  2 -1 -1 -1 -1 -1 -1  9]
