![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [14]:
import numpy

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [15]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea una matrix 3x3, con el valor que tu quieras

In [16]:
my_matrix = np.array ([[1,2,3], 
                       [4,5,6], 
                       [7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
x = np.full((3,3), True)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Ejercicio 4

Crea un array con dimensión (2,8,), con el contenido que tu quieras.

In [18]:
array_4 = np.array ([["a","b","c","d","e","f","g","h"], 
                     ["i","j","k","l","m","n","o","p"]])
print(array_4)

[['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
 ['i' 'j' 'k' 'l' 'm' 'n' 'o' 'p']]


In [19]:
arr = np.random.randint(0, 10, size=(2, 8))
print(arr)

[[1 8 8 9 6 3 6 8]
 [8 9 9 0 1 3 5 1]]


## Ejercicio 5
Extrae todos los impares de `my_array`

In [20]:
my_array = np.arange(10)
print(my_array)

#for x in my_array:
    #if x % 2 != 0:
        #print(x)

impares = [x for x in my_array if x % 2 != 0]
print(impares)

[0 1 2 3 4 5 6 7 8 9]
[1, 3, 5, 7, 9]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [21]:
my_array = np.arange(10)
new_array = my_array.copy()
new_array[new_array % 2 != 0] = -1

print(new_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
En un nuevo array, sustituye todos los impares de `my_array` por -1. 

Esta vez usa `where`

In [22]:
array_7 = my_array.copy()

print(np.where(array_7 % 2 != 0, -1, array_7))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 8
Convierte `my_array` en un nuevo array de dos dimensiones (las que tu quieras) mediante `reshape`.

In [23]:
my_array = np.arange(10)
my_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 9
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 10
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [25]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 11
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [26]:
my_array = np.arange(10)

array_11 = my_array * 10
print(array_11)

print(my_array[0])
print(my_array[-1])
print(my_array[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


In [27]:
for i in my_array:
    my_array[i] = my_array[i] * 10

print(my_array)

[ 0 10 20 30 40 50 60 70 80 90]


## Ejercicio 12
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [28]:
my_matrix = np.array ([[1,2,3], 
                       [4,5,6], 
                       [7,8,9]])

## Ejercicio 14
Crea un array con este contenido:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

__USANDO UNA SOLA FUNCION__. (No puedes crear manualmente el array con esos valores)

In [29]:
print(np.arange(1,50,3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea un array con este contenido:

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

__USANDO UNA SOLA FUNCION__. (No puedes crear manualmente el array con esos valores)

In [30]:
print(np.arange(4,1,-0.25))

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Crea un array de 4x1 y a continuación convierte el array a un 2x2

In [31]:
otro_array = np.array ([[1],
                        [2],
                        [3],
                        [4]])

otro_array.reshape(2,2)

array([[1, 2],
       [3, 4]])

## Ejercicio 17
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [32]:
ejer_17 = np.random.randint(10, 20, size = (4,5,3))
print(ejer_17)
ejer_17.ndim

[[[15 10 11]
  [16 14 19]
  [14 17 18]
  [17 14 13]
  [10 18 17]]

 [[18 19 16]
  [19 18 16]
  [18 12 18]
  [13 18 13]
  [12 15 14]]

 [[16 13 17]
  [18 12 15]
  [11 13 19]
  [11 10 11]
  [10 10 11]]

 [[12 16 19]
  [15 19 11]
  [15 17 16]
  [10 10 12]
  [13 19 10]]]


3

## Ejercicio 18
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [33]:
ejer_18 = np.full ((10,1), False)
print(ejer_18)

ejer_18.reshape(2,5)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 19
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [34]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)

print(x.size)
print(x.ndim)
print(x.shape)

[[[11 15 10 14 13 10]
  [19 10 12 11 17 15]]

 [[14 11 17 19 16 17]
  [17 14 14 11 11 13]]

 [[10 11 17 19 18 12]
  [14 14 12 19 17 19]]

 [[10 13 10 11 19 15]
  [12 18 19 13 15 17]]

 [[11 18 13 15 17 14]
  [15 16 10 13 18 11]]]
60
3
(5, 2, 6)
